# Generated by Django 3.0.8 on 2020-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
