# Generated by Django 3.0.8 on 2020-12-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20200714_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='room_no',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subjects',
            new_name='subjects_taught',
        ),
    ]
