# Generated by Django 3.0.8 on 2020-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20201205_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room_number',
            field=models.CharField(max_length=100, verbose_name='Room Number'),
        ),
    ]
